# Generated by Django 3.2.3 on 2021-05-24 21:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Violation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_stamp', models.DateTimeField(auto_now=True)),
                ('car_id', models.CharField(max_length=25)),
                ('street', models.CharField(max_length=115)),
                ('violation_type', models.CharField(choices=[('Speed', 'Speed'), ('Traffic', 'Traffic')], max_length=25)),
                ('comments', models.TextField(default='N/A', max_length=455)),
            ],
            options={
                'verbose_name': 'Violation',
                'verbose_name_plural': 'Violations',
            },
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('car_id', models.CharField(max_length=115, primary_key=True, serialize=False, unique=True, verbose_name='Car ID')),
                ('car_type', models.CharField(max_length=25, verbose_name='Car Type')),
                ('num_passengers', models.IntegerField(default=4, verbose_name='Number of Passengers')),
                ('car_owner', models.CharField(max_length=455, verbose_name='Car Owner')),
                ('location', models.CharField(max_length=115, verbose_name='Location')),
                ('violations', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.violation')),
            ],
            options={
                'verbose_name': 'Car',
                'verbose_name_plural': 'Cars',
            },
        ),
    ]
