# Generated by Django 3.2.3 on 2021-05-28 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='violations',
        ),
        migrations.AddField(
            model_name='car',
            name='violations',
            field=models.ManyToManyField(blank=True, null=True, to='main.Violation'),
        ),
    ]
