# Generated by Django 3.2.3 on 2021-06-01 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210528_0416'),
    ]

    operations = [
        migrations.CreateModel(
            name='Traffic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=1000)),
            ],
            options={
                'verbose_name': 'Traffic System',
                'verbose_name_plural': 'Traffic Systems',
            },
        ),
    ]
