# Generated by Django 3.2.3 on 2021-06-08 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_violation_violation_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='violation',
            name='latitude',
            field=models.CharField(default='.', max_length=115),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='violation',
            name='longitude',
            field=models.CharField(default='.', max_length=115),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='violation',
            name='street',
            field=models.CharField(blank=True, max_length=115, null=True),
        ),
    ]
