# Generated by Django 3.2.3 on 2021-06-12 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_car_car_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='car_id',
            field=models.CharField(max_length=115, primary_key=True, serialize=False, unique=True, verbose_name='Car ID'),
        ),
    ]
