# Generated by Django 3.2.3 on 2021-06-13 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_car_car_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='violations',
        ),
        migrations.RemoveField(
            model_name='violation',
            name='car_id',
        ),
        migrations.AddField(
            model_name='violation',
            name='car',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.car'),
        ),
        migrations.AlterField(
            model_name='car',
            name='car_id',
            field=models.CharField(max_length=255, primary_key=True, serialize=False, unique=True, verbose_name='Car ID'),
        ),
        migrations.AlterField(
            model_name='car',
            name='car_owner',
            field=models.CharField(max_length=255, verbose_name='Car Owner'),
        ),
        migrations.AlterField(
            model_name='car',
            name='car_type',
            field=models.CharField(max_length=255, verbose_name='Car Type'),
        ),
        migrations.AlterField(
            model_name='car',
            name='location',
            field=models.CharField(max_length=255, verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='violation',
            name='comments',
            field=models.TextField(default='N/A', max_length=255),
        ),
        migrations.AlterField(
            model_name='violation',
            name='latitude',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='violation',
            name='longitude',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='violation',
            name='street',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='violation',
            name='violation_type',
            field=models.CharField(choices=[('Speed', 'Speed'), ('Red Light', 'Red Light'), ('Taligating', 'Taligating'), ('Emergency Vehicle', 'Emergency Vehicle'), ('Carpool', 'Carpool')], max_length=255),
        ),
    ]
