# Generated by Django 3.2.3 on 2021-06-13 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_violation_car'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='violation',
            name='car',
        ),
        migrations.AddField(
            model_name='car',
            name='violations',
            field=models.ManyToManyField(blank=True, null=True, to='main.Violation'),
        ),
        migrations.AddField(
            model_name='violation',
            name='car_id',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='violation',
            name='violation_type',
            field=models.CharField(max_length=255),
        ),
    ]
