# Generated by Django 3.2.3 on 2021-06-13 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20210613_1841'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='violations',
        ),
        migrations.RemoveField(
            model_name='violation',
            name='car_id',
        ),
        migrations.AddField(
            model_name='violation',
            name='car',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.car'),
        ),
    ]
