# Generated by Django 3.2.3 on 2021-06-13 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_violation_car'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='car_id',
            field=models.CharField(editable=False, max_length=255, primary_key=True, serialize=False, unique=True, verbose_name='Car ID'),
        ),
    ]
