# Generated by Django 3.2.3 on 2021-06-19 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_car_car_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='car_id',
            field=models.CharField(max_length=10000, primary_key=True, serialize=False, unique=True, verbose_name='Car ID'),
        ),
        migrations.AlterField(
            model_name='violation',
            name='violation_type',
            field=models.CharField(choices=[('Speed', 'Speed'), ('Emergency Vehicle', 'Emergency Vehicle'), ('Tailgating', 'Tailgating'), ('Red Light', 'Red Light'), ('Carpool', 'Carpool')], max_length=255),
        ),
    ]
