# Generated by Django 3.2.3 on 2021-06-19 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20210619_1848'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='violation',
            name='car',
        ),
    ]
