# Generated by Django 3.2.3 on 2021-06-19 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_remove_violation_car'),
    ]

    operations = [
        migrations.AddField(
            model_name='violation',
            name='car_id',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
