# Generated by Django 3.2.3 on 2021-06-19 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_auto_20210619_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='violation',
            name='car',
            field=models.CharField(max_length=255),
        ),
    ]
