# Generated by Django 3.2.3 on 2021-06-19 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_alter_violation_car'),
    ]

    operations = [
        migrations.AlterField(
            model_name='violation',
            name='car',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
