# Generated by Django 3.2.3 on 2021-06-25 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_alter_violation_car'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='car_type',
            field=models.CharField(choices=[('Auto', 'Auto'), ('Truck', 'Truck')], max_length=255, verbose_name='Car Type'),
        ),
    ]
