# Generated by Django 3.2.3 on 2021-06-25 23:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_alter_car_car_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='location',
        ),
        migrations.AddField(
            model_name='car',
            name='plate_num',
            field=models.CharField(default='TEST', max_length=255, verbose_name='Plate Number'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='violation',
            name='car',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.car'),
            preserve_default=False,
        ),
    ]
