# Generated by Django 3.2.3 on 2021-06-26 12:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_auto_20210625_2340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='violation',
            name='time_stamp',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
