# Generated by Django 3.2.3 on 2021-06-26 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_alter_violation_time_stamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='violation',
            name='street',
        ),
    ]
